/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          orange: '#ff5a1f',
          dark: '#0a1128',
          card: '#15203b',
          info: '#eff6ff',
          infoText: '#1e3a8a',
        },
        "on-tertiary-fixed-variant": "#004786",
        "surface": "#f8f9ff",
        "inverse-primary": "#ffb68d",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9ff",
        "primary-fixed-dim": "#ffb68d",
        "secondary-fixed-dim": "#bfc6dc",
        "on-secondary-fixed": "#141b2c",
        "tertiary-container": "#70acff",
        "surface-container": "#e6eeff",
        "tertiary": "#005fb0",
        "secondary-container": "#dbe2f9",
        "on-surface": "#0f1c2d",
        "background": "#f8f9ff",
        "tertiary-fixed-dim": "#a6c8ff",
        "surface-container-high": "#dce9ff",
        "surface-tint": "#9b4500",
        "on-primary-fixed-variant": "#763300",
        "primary-fixed": "#ffdbc9",
        "outline-variant": "#ddc1b3",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#dbe2f9",
        "on-surface-variant": "#564338",
        "on-background": "#0f1c2d",
        "inverse-surface": "#243143",
        "primary-container": "#ff8c42",
        "surface-container-low": "#eff4ff",
        "inverse-on-surface": "#eaf1ff",
        "surface-variant": "#d6e3fb",
        "on-primary-fixed": "#331200",
        "on-secondary-container": "#5c6477",
        "on-secondary-fixed-variant": "#3f4759",
        "on-tertiary-container": "#003f78",
        "outline": "#897266",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "surface-dim": "#cddbf2",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#d6e3fb",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-container": "#6a2d00",
        "secondary": "#565e71",
        "tertiary-fixed": "#d5e3ff",
        "primary": "#9b4500",
        "on-tertiary-fixed": "#001c3b"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sidebar-width": "230px",
        "container-padding": "32px",
        "stack-md": "16px",
        "gutter": "24px",
        "header-height": "64px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "headline-md": ["Inter"],
        "kpi-number": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"]
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "kpi-number": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
