import { useState } from 'react';
import MaterialIcon from '../atoms/MaterialIcon';

const DETAILS_MAP = {
  'INC-2024-892': {
    description: 'Unauthorized access attempt detected at Sector 4 Voting Node cluster. Multiple failed authentication pings originating from external IP range outside standard operational parameters. Local team isolated the node, but secondary systems show elevated latency indicating potential ongoing network stress. Immediate escalation required to secure regional data integrity.',
    location: 'Abuja, Central District', category: 'Security Breach',
    reporter: 'Agent K. Olayinka', time: '14:32 WAT Today',
    critical: true,
    timeline: [
      { icon: 'warning', color: '#EF4444', bg: '#FEE2E2', label: 'Classification Updated', time: '14:45', detail: 'System automatically upgraded severity to Critical based on sustained latency metrics.', highlight: 'Critical', tag: true },
      { icon: 'person', color: '#2563EB', bg: '#DBEAFE', label: 'Agent Assigned', time: '14:35', detail: 'Incident routed to Cyber-Sec Response Team Alpha.' },
      { icon: 'lock', color: '#6B7280', bg: '#F3F4F6', label: 'Incident Created', time: '14:32', detail: 'Initial alert generated by Node Monitoring System.', code: '> NODE_4_AUTH_FAIL_RATE_EXCEEDED\n> SOURCE: 192.168.x.x' },
    ],
    entities: [{ icon: 'hub', label: 'Node Cluster 4' }, { icon: 'policy', label: 'Security Protocol B' }],
    coords: '9.0765° N, 7.3986° E',
  },
  'INC-2024-891': {
    description: 'Complete connectivity loss reported at Lagos results collation center. Multiple BVAS devices unable to sync due to network outage. Backup 4G modems have been deployed but bandwidth insufficient for real-time data uploads.',
    location: 'Lagos, Ikeja LGA', category: 'Technical Failure',
    reporter: 'A. Doe', time: '10:15 WAT Today',
    critical: false,
    timeline: [
      { icon: 'settings', color: '#8B5CF6', bg: '#EDE9FE', label: 'Technician Dispatched', time: '10:30', detail: 'Field technician deployed to site.' },
      { icon: 'lock', color: '#6B7280', bg: '#F3F4F6', label: 'Incident Created', time: '10:15', detail: 'Network outage reported by collation officer.' },
    ],
    entities: [{ icon: 'router', label: 'Network Hub B2' }, { icon: 'computer', label: 'BVAS Unit 07' }],
    coords: '6.5244° N, 3.3792° E',
  },
};

const FALLBACK = {
  description: 'Incident details are being gathered. Please check back shortly.',
  location: 'Unknown', category: 'Under Review',
  reporter: 'System', time: 'Today',
  critical: false, timeline: [], entities: [], coords: 'N/A',
};

export default function IncidentDetailDrawer({ incident, onClose }) {
  const [note, setNote] = useState('');
  if (!incident) return null;
  const d = DETAILS_MAP[incident.id] || { ...FALLBACK, location: incident.location + ', ' + incident.sub, category: incident.category, reporter: 'Field Officer', time: incident.time + ' Today' };

  return (
    <>
      {/* Backdrop */}
      <div onClick={onClose} style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.28)', zIndex: 200, backdropFilter: 'blur(1px)' }} />

      {/* Wide panel */}
      <div style={{ position: 'fixed', top: 0, right: 0, bottom: 0, width: 860, background: '#F8FAFC', zIndex: 201, display: 'flex', flexDirection: 'column', boxShadow: '-8px 0 40px rgba(0,0,0,0.15)', animation: 'incIn .22s cubic-bezier(.4,0,.2,1)', overflowY: 'auto' }}>
        <style>{`@keyframes incIn{from{transform:translateX(100%)}to{transform:translateX(0)}}`}</style>

        {/* ── Top bar ── */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 22px', background: '#fff', borderBottom: '1px solid #E5E7EB', flexShrink: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <span style={{ fontSize: 13, fontWeight: 700, color: '#111827' }}>{incident.id}</span>
            <span style={{ fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 999, background: incident.severity === 'Critical' ? '#FEE2E2' : incident.severity === 'High' ? '#FFEDD5' : '#FEF9C3', color: incident.severity === 'Critical' ? '#DC2626' : incident.severity === 'High' ? '#EA580C' : '#CA8A04' }}>{incident.severity}</span>
          </div>
          <button onClick={onClose} style={{ width: 30, height: 30, border: 'none', background: '#F3F4F6', borderRadius: 6, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#6B7280' }}>
            <MaterialIcon icon="close" className="text-[16px]" />
          </button>
        </div>

        {/* ── Two-column layout ── */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 320px', gap: 0, flex: 1, minHeight: 0 }}>

          {/* LEFT column */}
          <div style={{ padding: 20, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 16 }}>

            {/* Incident Overview card */}
            <div style={{ background: '#fff', borderRadius: 12, border: '1px solid #E5E7EB', padding: 20 }}>
              <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 12 }}>
                <div>
                  <h2 style={{ margin: 0, fontSize: 16, fontWeight: 700, color: '#111827' }}>Incident Overview</h2>
                  <p style={{ margin: '3px 0 0', fontSize: 12, color: '#9CA3AF' }}>Detailed situation report and initial assessment.</p>
                </div>
                <button style={{ width: 28, height: 28, border: '1px solid #E5E7EB', borderRadius: 6, background: '#fff', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#6B7280' }}>
                  <MaterialIcon icon="edit" className="text-[13px]" />
                </button>
              </div>

              <div style={{ marginBottom: 16 }}>
                <div style={{ fontSize: 10, fontWeight: 700, color: '#9CA3AF', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 6 }}>DESCRIPTION</div>
                <p style={{ margin: 0, fontSize: 13, color: '#374151', lineHeight: 1.65 }}>{d.description}</p>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 14, paddingTop: 14, borderTop: '1px solid #F3F4F6' }}>
                {[
                  { label: 'LOCATION', icon: 'location_on', color: '#EA580C', val: d.location },
                  { label: 'CATEGORY', icon: 'label', color: '#8B5CF6', val: d.category },
                  { label: 'REPORTED BY', icon: 'person', color: '#2563EB', val: d.reporter },
                  { label: 'TIME DETECTED', icon: 'schedule', color: '#16A34A', val: d.time },
                ].map((f) => (
                  <div key={f.label}>
                    <div style={{ fontSize: 10, fontWeight: 600, color: '#9CA3AF', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>{f.label}</div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
                      <MaterialIcon icon={f.icon} className="text-[13px]" style={{ color: f.color, flexShrink: 0 }} />
                      <span style={{ fontSize: 12, fontWeight: 600, color: '#111827' }}>{f.val}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Geospatial Context */}
            <div style={{ background: '#fff', borderRadius: 12, border: '1px solid #E5E7EB', overflow: 'hidden' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 18px', borderBottom: '1px solid #F3F4F6' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 7 }}>
                  <MaterialIcon icon="map" className="text-[15px]" style={{ color: '#6B7280' }} />
                  <span style={{ fontSize: 13, fontWeight: 600, color: '#111827' }}>Geospatial Context</span>
                </div>
                <span style={{ fontSize: 11, color: '#9CA3AF' }}>Coordinates: {d.coords}</span>
              </div>
              {/* Map placeholder */}
              <div style={{ height: 220, background: '#E8EEF4', position: 'relative', overflow: 'hidden' }}>
                <svg width="100%" height="100%" viewBox="0 0 600 220" preserveAspectRatio="xMidYMid slice">
                  {/* Grid lines simulating map */}
                  {[...Array(12)].map((_, i) => <line key={`v${i}`} x1={i*55} y1="0" x2={i*55} y2="220" stroke="#D1D5DB" strokeWidth="0.5" />)}
                  {[...Array(6)].map((_,  i) => <line key={`h${i}`} x1="0" y1={i*44} x2="600" y2={i*44} stroke="#D1D5DB" strokeWidth="0.5" />)}
                  {/* Roads */}
                  <rect x="120" y="0" width="18" height="220" fill="#C9D3DC" opacity="0.6" />
                  <rect x="0" y="90" width="600" height="16" fill="#C9D3DC" opacity="0.6" />
                  <rect x="280" y="0" width="14" height="220" fill="#C9D3DC" opacity="0.5" />
                  <rect x="0" y="158" width="600" height="12" fill="#C9D3DC" opacity="0.4" />
                  {/* City blocks */}
                  {[[20,20,90,64],[145,20,120,64],[285,20,85,64],[380,20,100,64],[490,20,105,64],[20,110,90,42],[145,110,120,42],[285,110,85,42],[380,110,100,42],[20,158,90,58],[145,160,120,54],[285,160,85,54],[380,160,100,54]].map(([x,y,w,h],i)=>(
                    <rect key={i} x={x} y={y} width={w} height={h} fill="#CBD5E1" rx="3" opacity="0.5" />
                  ))}
                  {/* Incident marker with pulse */}
                  <circle cx="300" cy="110" r="28" fill="#EF4444" opacity="0.12" />
                  <circle cx="300" cy="110" r="18" fill="#EF4444" opacity="0.2" />
                  <circle cx="300" cy="110" r="10" fill="#EF4444" opacity="0.9" />
                  <circle cx="300" cy="110" r="4" fill="#fff" />
                  <text x="314" y="104" fontSize="9" fontWeight="700" fill="#DC2626">INCIDENT {incident.id.slice(-3)}</text>
                </svg>
                <div style={{ position: 'absolute', bottom: 10, right: 10, background: 'rgba(255,255,255,0.9)', borderRadius: 6, padding: '4px 10px', fontSize: 11, fontWeight: 500, color: '#374151' }}>
                  📍 Legend
                </div>
                {/* Zoom controls */}
                <div style={{ position: 'absolute', top: 10, right: 10, display: 'flex', flexDirection: 'column', background: '#fff', borderRadius: 6, border: '1px solid #E5E7EB', overflow: 'hidden' }}>
                  {['+', '−'].map((s) => <button key={s} style={{ width: 28, height: 28, border: 'none', background: 'none', cursor: 'pointer', fontSize: 16, color: '#374151', lineHeight: 1 }}>{s}</button>)}
                </div>
              </div>
            </div>

            {/* Alert banner */}
            {d.critical && (
              <div style={{ background: '#1F2937', borderRadius: 12, padding: '18px 20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 14 }}>
                <div style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
                  <div style={{ width: 32, height: 32, borderRadius: 8, background: 'rgba(239,68,68,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                    <MaterialIcon icon="warning_amber" className="text-[16px]" style={{ color: '#F87171' }} />
                  </div>
                  <div>
                    <div style={{ fontSize: 14, fontWeight: 700, color: '#fff', marginBottom: 4 }}>Incident requires immediate escalation</div>
                    <div style={{ fontSize: 12, color: '#9CA3AF', lineHeight: 1.5 }}>Protocol mandates escalation to National Director within 15 minutes of Critical classification.</div>
                  </div>
                </div>
                <div style={{ display: 'flex', gap: 8, flexShrink: 0 }}>
                  <button style={{ height: 34, padding: '0 14px', borderRadius: 8, border: '1px solid #4B5563', background: 'transparent', fontSize: 12, fontWeight: 600, color: '#D1D5DB', cursor: 'pointer' }}>Create Report</button>
                  <button style={{ height: 34, padding: '0 14px', borderRadius: 8, border: 'none', background: '#EF4444', fontSize: 12, fontWeight: 700, color: '#fff', cursor: 'pointer' }}>Escalate Now</button>
                </div>
              </div>
            )}
          </div>

          {/* RIGHT column */}
          <div style={{ background: '#fff', borderLeft: '1px solid #E5E7EB', padding: 18, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 20 }}>

            {/* Incident Timeline */}
            <div>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
                <span style={{ fontSize: 13, fontWeight: 700, color: '#111827' }}>Incident Timeline</span>
                <button style={{ height: 26, padding: '0 10px', border: '1px solid #E5E7EB', borderRadius: 6, background: '#fff', fontSize: 11, fontWeight: 500, color: '#6B7280', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4 }}>
                  <MaterialIcon icon="filter_list" className="text-[12px]" /> Filter
                </button>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
                {d.timeline.map((t, i) => (
                  <div key={i} style={{ display: 'flex', gap: 12, paddingBottom: 18, position: 'relative' }}>
                    {i < d.timeline.length - 1 && <div style={{ position: 'absolute', left: 15, top: 34, bottom: 0, width: 2, background: '#F3F4F6' }} />}
                    <div style={{ width: 32, height: 32, borderRadius: '50%', background: t.bg, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, zIndex: 1 }}>
                      <MaterialIcon icon={t.icon} className="text-[14px]" style={{ color: t.color }} />
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 3 }}>
                        <span style={{ fontSize: 12, fontWeight: 700, color: '#111827' }}>{t.label}</span>
                        <span style={{ fontSize: 11, color: '#9CA3AF' }}>{t.time}</span>
                      </div>
                      <p style={{ margin: 0, fontSize: 12, color: '#6B7280', lineHeight: 1.5 }}>
                        {t.tag ? t.detail.replace('Critical', '') : t.detail}
                        {t.tag && <span style={{ fontSize: 11, fontWeight: 700, padding: '1px 6px', borderRadius: 999, background: '#FEE2E2', color: '#DC2626', marginLeft: 4 }}>Critical</span>}
                      </p>
                      {t.code && (
                        <pre style={{ margin: '6px 0 0', padding: '8px 10px', background: '#111827', borderRadius: 6, fontSize: 10, color: '#86EFAC', lineHeight: 1.6, overflow: 'auto', fontFamily: 'monospace' }}>
                          {t.code}
                        </pre>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Add internal note */}
            <div style={{ borderTop: '1px solid #F3F4F6', paddingTop: 16 }}>
              <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                <input
                  value={note} onChange={(e) => setNote(e.target.value)}
                  placeholder="Add an internal note..."
                  style={{ flex: 1, height: 34, padding: '0 12px', fontSize: 12, border: '1px solid #E5E7EB', borderRadius: 8, outline: 'none', color: '#374151' }}
                />
                <button style={{ width: 34, height: 34, border: 'none', background: '#FF5A1F', borderRadius: 8, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <MaterialIcon icon="send" className="text-[14px]" style={{ color: '#fff' }} />
                </button>
              </div>
            </div>

            {/* Related Entities */}
            {d.entities.length > 0 && (
              <div style={{ borderTop: '1px solid #F3F4F6', paddingTop: 16 }}>
                <div style={{ fontSize: 11, fontWeight: 700, color: '#9CA3AF', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>RELATED ENTITIES</div>
                {d.entities.map((e) => (
                  <div key={e.label} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 10px', border: '1px solid #E5E7EB', borderRadius: 8, marginBottom: 8, cursor: 'pointer' }}
                    onMouseEnter={(el) => el.currentTarget.style.background = '#FAFAFA'}
                    onMouseLeave={(el) => el.currentTarget.style.background = '#fff'}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <MaterialIcon icon={e.icon} className="text-[14px]" style={{ color: '#6B7280' }} />
                      <span style={{ fontSize: 12, fontWeight: 600, color: '#374151' }}>{e.label}</span>
                    </div>
                    <MaterialIcon icon="open_in_new" className="text-[13px]" style={{ color: '#9CA3AF' }} />
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
}
